package info.chengjie.domain;


import javax.persistence.*

@Entity
@Table(name = "user")
class User {

    // ==============
    // PRIVATE FIELDS
    // ==============
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    long id

    // The user email

    String mobile;
    // The user name
    String username

    int gender
    int age
    String avatar
    Date created_at
    Date updated_at
    String latitude
    String longitude
    String geohash
    int trade_id
    String career
    int province_id
    int city_id
    int area_id
    int type
    int current_bp
    int next_bp
    int support_im
    int from_user_id




}